// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: relay/notification/v1/notification_configuration_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Relay.Notification.V1 {
  public static partial class NotificationConfiguration
  {
    static readonly string __ServiceName = "relay.notification.v1.NotificationConfiguration";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Notification.V1.CreateWebhookConfigurationRequest> __Marshaller_relay_notification_v1_CreateWebhookConfigurationRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Notification.V1.CreateWebhookConfigurationRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Notification.V1.CreateWebhookConfigurationResponse> __Marshaller_relay_notification_v1_CreateWebhookConfigurationResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Notification.V1.CreateWebhookConfigurationResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Notification.V1.GetConfigurationRequest> __Marshaller_relay_notification_v1_GetConfigurationRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Notification.V1.GetConfigurationRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Notification.V1.GetConfigurationResponse> __Marshaller_relay_notification_v1_GetConfigurationResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Notification.V1.GetConfigurationResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Notification.V1.DeleteConfigurationRequest> __Marshaller_relay_notification_v1_DeleteConfigurationRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Notification.V1.DeleteConfigurationRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Notification.V1.DeleteConfigurationResponse> __Marshaller_relay_notification_v1_DeleteConfigurationResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Notification.V1.DeleteConfigurationResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Relay.Notification.V1.CreateWebhookConfigurationRequest, global::Relay.Notification.V1.CreateWebhookConfigurationResponse> __Method_CreateWebhookConfiguration = new grpc::Method<global::Relay.Notification.V1.CreateWebhookConfigurationRequest, global::Relay.Notification.V1.CreateWebhookConfigurationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateWebhookConfiguration",
        __Marshaller_relay_notification_v1_CreateWebhookConfigurationRequest,
        __Marshaller_relay_notification_v1_CreateWebhookConfigurationResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Relay.Notification.V1.GetConfigurationRequest, global::Relay.Notification.V1.GetConfigurationResponse> __Method_Get = new grpc::Method<global::Relay.Notification.V1.GetConfigurationRequest, global::Relay.Notification.V1.GetConfigurationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_relay_notification_v1_GetConfigurationRequest,
        __Marshaller_relay_notification_v1_GetConfigurationResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Relay.Notification.V1.DeleteConfigurationRequest, global::Relay.Notification.V1.DeleteConfigurationResponse> __Method_Delete = new grpc::Method<global::Relay.Notification.V1.DeleteConfigurationRequest, global::Relay.Notification.V1.DeleteConfigurationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Delete",
        __Marshaller_relay_notification_v1_DeleteConfigurationRequest,
        __Marshaller_relay_notification_v1_DeleteConfigurationResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Relay.Notification.V1.NotificationConfigurationServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of NotificationConfiguration</summary>
    [grpc::BindServiceMethod(typeof(NotificationConfiguration), "BindService")]
    public abstract partial class NotificationConfigurationBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Relay.Notification.V1.CreateWebhookConfigurationResponse> CreateWebhookConfiguration(global::Relay.Notification.V1.CreateWebhookConfigurationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Relay.Notification.V1.GetConfigurationResponse> Get(global::Relay.Notification.V1.GetConfigurationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Relay.Notification.V1.DeleteConfigurationResponse> Delete(global::Relay.Notification.V1.DeleteConfigurationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for NotificationConfiguration</summary>
    public partial class NotificationConfigurationClient : grpc::ClientBase<NotificationConfigurationClient>
    {
      /// <summary>Creates a new client for NotificationConfiguration</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public NotificationConfigurationClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NotificationConfiguration that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public NotificationConfigurationClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected NotificationConfigurationClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected NotificationConfigurationClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Notification.V1.CreateWebhookConfigurationResponse CreateWebhookConfiguration(global::Relay.Notification.V1.CreateWebhookConfigurationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateWebhookConfiguration(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Notification.V1.CreateWebhookConfigurationResponse CreateWebhookConfiguration(global::Relay.Notification.V1.CreateWebhookConfigurationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateWebhookConfiguration, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Notification.V1.CreateWebhookConfigurationResponse> CreateWebhookConfigurationAsync(global::Relay.Notification.V1.CreateWebhookConfigurationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateWebhookConfigurationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Notification.V1.CreateWebhookConfigurationResponse> CreateWebhookConfigurationAsync(global::Relay.Notification.V1.CreateWebhookConfigurationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateWebhookConfiguration, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Notification.V1.GetConfigurationResponse Get(global::Relay.Notification.V1.GetConfigurationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Get(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Notification.V1.GetConfigurationResponse Get(global::Relay.Notification.V1.GetConfigurationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Get, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Notification.V1.GetConfigurationResponse> GetAsync(global::Relay.Notification.V1.GetConfigurationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Notification.V1.GetConfigurationResponse> GetAsync(global::Relay.Notification.V1.GetConfigurationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Get, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Notification.V1.DeleteConfigurationResponse Delete(global::Relay.Notification.V1.DeleteConfigurationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Delete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Notification.V1.DeleteConfigurationResponse Delete(global::Relay.Notification.V1.DeleteConfigurationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Delete, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Notification.V1.DeleteConfigurationResponse> DeleteAsync(global::Relay.Notification.V1.DeleteConfigurationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Notification.V1.DeleteConfigurationResponse> DeleteAsync(global::Relay.Notification.V1.DeleteConfigurationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Delete, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override NotificationConfigurationClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NotificationConfigurationClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(NotificationConfigurationBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateWebhookConfiguration, serviceImpl.CreateWebhookConfiguration)
          .AddMethod(__Method_Get, serviceImpl.Get)
          .AddMethod(__Method_Delete, serviceImpl.Delete).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, NotificationConfigurationBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateWebhookConfiguration, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Relay.Notification.V1.CreateWebhookConfigurationRequest, global::Relay.Notification.V1.CreateWebhookConfigurationResponse>(serviceImpl.CreateWebhookConfiguration));
      serviceBinder.AddMethod(__Method_Get, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Relay.Notification.V1.GetConfigurationRequest, global::Relay.Notification.V1.GetConfigurationResponse>(serviceImpl.Get));
      serviceBinder.AddMethod(__Method_Delete, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Relay.Notification.V1.DeleteConfigurationRequest, global::Relay.Notification.V1.DeleteConfigurationResponse>(serviceImpl.Delete));
    }

  }
}
#endregion
