// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: relay/processing/v1/payment_processing_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Relay.Processing.V1 {

  /// <summary>Holder for reflection information generated from relay/processing/v1/payment_processing_service.proto</summary>
  public static partial class PaymentProcessingServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for relay/processing/v1/payment_processing_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PaymentProcessingServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjRyZWxheS9wcm9jZXNzaW5nL3YxL3BheW1lbnRfcHJvY2Vzc2luZ19zZXJ2",
            "aWNlLnByb3RvEhNyZWxheS5wcm9jZXNzaW5nLnYxGhlnb29nbGUvcHJvdG9i",
            "dWYvYW55LnByb3RvGhJyZWxheS9tb2RlbHMucHJvdG8aIHJlbGF5L3Byb2Nl",
            "c3NpbmcvdjEvbW9kZWxzLnByb3RvItwBCg1DaGFyZ2VSZXF1ZXN0EicKH3Bh",
            "eW1lbnRfbWV0aG9kX2NvbmZpZ3VyYXRpb25faWQYASABKAkSEgoKcmVxdWVz",
            "dF9pZBgCIAEoCRIRCglyZWZlcmVuY2UYAyABKAkSLAoOcGF5bWVudF9tZXRo",
            "b2QYBCABKA4yFC5yZWxheS5QYXltZW50TWV0aG9kEikKBW9yZGVyGAUgASgL",
            "MhoucmVsYXkucHJvY2Vzc2luZy52MS5PcmRlchIiCgRkYXRhGGQgASgLMhQu",
            "Z29vZ2xlLnByb3RvYnVmLkFueSJ6Cg5DaGFyZ2VSZXNwb25zZRISCgpwYXlt",
            "ZW50X2lkGAEgASgJEhEKCWNoYXJnZV9pZBgCIAEoCRIiCgRkYXRhGGQgASgL",
            "MhQuZ29vZ2xlLnByb3RvYnVmLkFueRIdCgZzdGF0dXMYZSABKAsyDS5yZWxh",
            "eS5TdGF0dXMifgoNUmVmdW5kUmVxdWVzdBISCgpwYXltZW50X2lkGAEgASgJ",
            "EhIKCnJlcXVlc3RfaWQYAiABKAkSEQoJcmVmZXJlbmNlGAMgASgJEg4KBmFt",
            "b3VudBgEIAEoAxIiCgRkYXRhGGQgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFu",
            "eSJmCg5SZWZ1bmRSZXNwb25zZRIRCglyZWZ1bmRfaWQYASABKAkSIgoEZGF0",
            "YRhkIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnkSHQoGc3RhdHVzGGUgASgL",
            "Mg0ucmVsYXkuU3RhdHVzIicKEUdldFN1bW1hcnlSZXF1ZXN0EhIKCnBheW1l",
            "bnRfaWQYASABKAkiqgEKEkdldFN1bW1hcnlSZXNwb25zZRIZChFhdXRob3Jp",
            "emVkX2Ftb3VudBgBIAEoAxIWCg5jaGFyZ2VkX2Ftb3VudBgCIAEoAxIXCg9j",
            "YW5jZWxlZF9hbW91bnQYAyABKAMSFwoPcmVmdW5kZWRfYW1vdW50GAQgASgD",
            "EhAKCGN1cnJlbmN5GAUgASgJEh0KBnN0YXR1cxhlIAEoCzINLnJlbGF5LlN0",
            "YXR1cyIxChtHZXRPcGVyYXRpb25zU3VtbWFyeVJlcXVlc3QSEgoKcGF5bWVu",
            "dF9pZBgBIAEoCSJ4ChxHZXRPcGVyYXRpb25zU3VtbWFyeVJlc3BvbnNlEjkK",
            "Cm9wZXJhdGlvbnMYASADKAsyJS5yZWxheS5wcm9jZXNzaW5nLnYxLk9wZXJh",
            "dGlvblN1bW1hcnkSHQoGc3RhdHVzGGUgASgLMg0ucmVsYXkuU3RhdHVzMp0D",
            "ChFQYXltZW50UHJvY2Vzc2luZxJTCgZDaGFyZ2USIi5yZWxheS5wcm9jZXNz",
            "aW5nLnYxLkNoYXJnZVJlcXVlc3QaIy5yZWxheS5wcm9jZXNzaW5nLnYxLkNo",
            "YXJnZVJlc3BvbnNlIgASUwoGUmVmdW5kEiIucmVsYXkucHJvY2Vzc2luZy52",
            "MS5SZWZ1bmRSZXF1ZXN0GiMucmVsYXkucHJvY2Vzc2luZy52MS5SZWZ1bmRS",
            "ZXNwb25zZSIAEl8KCkdldFN1bW1hcnkSJi5yZWxheS5wcm9jZXNzaW5nLnYx",
            "LkdldFN1bW1hcnlSZXF1ZXN0GicucmVsYXkucHJvY2Vzc2luZy52MS5HZXRT",
            "dW1tYXJ5UmVzcG9uc2UiABJ9ChRHZXRPcGVyYXRpb25zU3VtbWFyeRIwLnJl",
            "bGF5LnByb2Nlc3NpbmcudjEuR2V0T3BlcmF0aW9uc1N1bW1hcnlSZXF1ZXN0",
            "GjEucmVsYXkucHJvY2Vzc2luZy52MS5HZXRPcGVyYXRpb25zU3VtbWFyeVJl",
            "c3BvbnNlIgBCTlo2Z2l0aHViLmNvbS9OZWR2ZWQ3NS9ncnBjdHNlL3Nkay9n",
            "by9yZWxheS9wcm9jZXNzaW5nL3YxqgITUmVsYXkuUHJvY2Vzc2luZy5WMWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::Relay.ModelsReflection.Descriptor, global::Relay.Processing.V1.ModelsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.ChargeRequest), global::Relay.Processing.V1.ChargeRequest.Parser, new[]{ "PaymentMethodConfigurationId", "RequestId", "Reference", "PaymentMethod", "Order", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.ChargeResponse), global::Relay.Processing.V1.ChargeResponse.Parser, new[]{ "PaymentId", "ChargeId", "Data", "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.RefundRequest), global::Relay.Processing.V1.RefundRequest.Parser, new[]{ "PaymentId", "RequestId", "Reference", "Amount", "Data" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.RefundResponse), global::Relay.Processing.V1.RefundResponse.Parser, new[]{ "RefundId", "Data", "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.GetSummaryRequest), global::Relay.Processing.V1.GetSummaryRequest.Parser, new[]{ "PaymentId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.GetSummaryResponse), global::Relay.Processing.V1.GetSummaryResponse.Parser, new[]{ "AuthorizedAmount", "ChargedAmount", "CanceledAmount", "RefundedAmount", "Currency", "Status" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.GetOperationsSummaryRequest), global::Relay.Processing.V1.GetOperationsSummaryRequest.Parser, new[]{ "PaymentId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Relay.Processing.V1.GetOperationsSummaryResponse), global::Relay.Processing.V1.GetOperationsSummaryResponse.Parser, new[]{ "Operations", "Status" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ChargeRequest : pb::IMessage<ChargeRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChargeRequest> _parser = new pb::MessageParser<ChargeRequest>(() => new ChargeRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChargeRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentProcessingServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChargeRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChargeRequest(ChargeRequest other) : this() {
      paymentMethodConfigurationId_ = other.paymentMethodConfigurationId_;
      requestId_ = other.requestId_;
      reference_ = other.reference_;
      paymentMethod_ = other.paymentMethod_;
      order_ = other.order_ != null ? other.order_.Clone() : null;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChargeRequest Clone() {
      return new ChargeRequest(this);
    }

    /// <summary>Field number for the "payment_method_configuration_id" field.</summary>
    public const int PaymentMethodConfigurationIdFieldNumber = 1;
    private string paymentMethodConfigurationId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PaymentMethodConfigurationId {
      get { return paymentMethodConfigurationId_; }
      set {
        paymentMethodConfigurationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 2;
    private string requestId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 3;
    private string reference_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Reference {
      get { return reference_; }
      set {
        reference_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "payment_method" field.</summary>
    public const int PaymentMethodFieldNumber = 4;
    private global::Relay.PaymentMethod paymentMethod_ = global::Relay.PaymentMethod.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Relay.PaymentMethod PaymentMethod {
      get { return paymentMethod_; }
      set {
        paymentMethod_ = value;
      }
    }

    /// <summary>Field number for the "order" field.</summary>
    public const int OrderFieldNumber = 5;
    private global::Relay.Processing.V1.Order order_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Relay.Processing.V1.Order Order {
      get { return order_; }
      set {
        order_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 100;
    private global::Google.Protobuf.WellKnownTypes.Any data_;
    /// <summary>
    /// Payment method specific information
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChargeRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChargeRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PaymentMethodConfigurationId != other.PaymentMethodConfigurationId) return false;
      if (RequestId != other.RequestId) return false;
      if (Reference != other.Reference) return false;
      if (PaymentMethod != other.PaymentMethod) return false;
      if (!object.Equals(Order, other.Order)) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PaymentMethodConfigurationId.Length != 0) hash ^= PaymentMethodConfigurationId.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (Reference.Length != 0) hash ^= Reference.GetHashCode();
      if (PaymentMethod != global::Relay.PaymentMethod.Unspecified) hash ^= PaymentMethod.GetHashCode();
      if (order_ != null) hash ^= Order.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PaymentMethodConfigurationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PaymentMethodConfigurationId);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestId);
      }
      if (Reference.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Reference);
      }
      if (PaymentMethod != global::Relay.PaymentMethod.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) PaymentMethod);
      }
      if (order_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Order);
      }
      if (data_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PaymentMethodConfigurationId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PaymentMethodConfigurationId);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestId);
      }
      if (Reference.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Reference);
      }
      if (PaymentMethod != global::Relay.PaymentMethod.Unspecified) {
        output.WriteRawTag(32);
        output.WriteEnum((int) PaymentMethod);
      }
      if (order_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Order);
      }
      if (data_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PaymentMethodConfigurationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PaymentMethodConfigurationId);
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (Reference.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Reference);
      }
      if (PaymentMethod != global::Relay.PaymentMethod.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PaymentMethod);
      }
      if (order_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Order);
      }
      if (data_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChargeRequest other) {
      if (other == null) {
        return;
      }
      if (other.PaymentMethodConfigurationId.Length != 0) {
        PaymentMethodConfigurationId = other.PaymentMethodConfigurationId;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.Reference.Length != 0) {
        Reference = other.Reference;
      }
      if (other.PaymentMethod != global::Relay.PaymentMethod.Unspecified) {
        PaymentMethod = other.PaymentMethod;
      }
      if (other.order_ != null) {
        if (order_ == null) {
          Order = new global::Relay.Processing.V1.Order();
        }
        Order.MergeFrom(other.Order);
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PaymentMethodConfigurationId = input.ReadString();
            break;
          }
          case 18: {
            RequestId = input.ReadString();
            break;
          }
          case 26: {
            Reference = input.ReadString();
            break;
          }
          case 32: {
            PaymentMethod = (global::Relay.PaymentMethod) input.ReadEnum();
            break;
          }
          case 42: {
            if (order_ == null) {
              Order = new global::Relay.Processing.V1.Order();
            }
            input.ReadMessage(Order);
            break;
          }
          case 802: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PaymentMethodConfigurationId = input.ReadString();
            break;
          }
          case 18: {
            RequestId = input.ReadString();
            break;
          }
          case 26: {
            Reference = input.ReadString();
            break;
          }
          case 32: {
            PaymentMethod = (global::Relay.PaymentMethod) input.ReadEnum();
            break;
          }
          case 42: {
            if (order_ == null) {
              Order = new global::Relay.Processing.V1.Order();
            }
            input.ReadMessage(Order);
            break;
          }
          case 802: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ChargeResponse : pb::IMessage<ChargeResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChargeResponse> _parser = new pb::MessageParser<ChargeResponse>(() => new ChargeResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChargeResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentProcessingServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChargeResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChargeResponse(ChargeResponse other) : this() {
      paymentId_ = other.paymentId_;
      chargeId_ = other.chargeId_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      status_ = other.status_ != null ? other.status_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChargeResponse Clone() {
      return new ChargeResponse(this);
    }

    /// <summary>Field number for the "payment_id" field.</summary>
    public const int PaymentIdFieldNumber = 1;
    private string paymentId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PaymentId {
      get { return paymentId_; }
      set {
        paymentId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "charge_id" field.</summary>
    public const int ChargeIdFieldNumber = 2;
    private string chargeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ChargeId {
      get { return chargeId_; }
      set {
        chargeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 100;
    private global::Google.Protobuf.WellKnownTypes.Any data_;
    /// <summary>
    /// Payment method specific information
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 101;
    private global::Relay.Status status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Relay.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChargeResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChargeResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PaymentId != other.PaymentId) return false;
      if (ChargeId != other.ChargeId) return false;
      if (!object.Equals(Data, other.Data)) return false;
      if (!object.Equals(Status, other.Status)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PaymentId.Length != 0) hash ^= PaymentId.GetHashCode();
      if (ChargeId.Length != 0) hash ^= ChargeId.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (status_ != null) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PaymentId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PaymentId);
      }
      if (ChargeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ChargeId);
      }
      if (data_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(Data);
      }
      if (status_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PaymentId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PaymentId);
      }
      if (ChargeId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ChargeId);
      }
      if (data_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(Data);
      }
      if (status_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PaymentId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PaymentId);
      }
      if (ChargeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChargeId);
      }
      if (data_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (status_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChargeResponse other) {
      if (other == null) {
        return;
      }
      if (other.PaymentId.Length != 0) {
        PaymentId = other.PaymentId;
      }
      if (other.ChargeId.Length != 0) {
        ChargeId = other.ChargeId;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Data.MergeFrom(other.Data);
      }
      if (other.status_ != null) {
        if (status_ == null) {
          Status = new global::Relay.Status();
        }
        Status.MergeFrom(other.Status);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PaymentId = input.ReadString();
            break;
          }
          case 18: {
            ChargeId = input.ReadString();
            break;
          }
          case 802: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Data);
            break;
          }
          case 810: {
            if (status_ == null) {
              Status = new global::Relay.Status();
            }
            input.ReadMessage(Status);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PaymentId = input.ReadString();
            break;
          }
          case 18: {
            ChargeId = input.ReadString();
            break;
          }
          case 802: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Data);
            break;
          }
          case 810: {
            if (status_ == null) {
              Status = new global::Relay.Status();
            }
            input.ReadMessage(Status);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RefundRequest : pb::IMessage<RefundRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RefundRequest> _parser = new pb::MessageParser<RefundRequest>(() => new RefundRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RefundRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentProcessingServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefundRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefundRequest(RefundRequest other) : this() {
      paymentId_ = other.paymentId_;
      requestId_ = other.requestId_;
      reference_ = other.reference_;
      amount_ = other.amount_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefundRequest Clone() {
      return new RefundRequest(this);
    }

    /// <summary>Field number for the "payment_id" field.</summary>
    public const int PaymentIdFieldNumber = 1;
    private string paymentId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PaymentId {
      get { return paymentId_; }
      set {
        paymentId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "request_id" field.</summary>
    public const int RequestIdFieldNumber = 2;
    private string requestId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "reference" field.</summary>
    public const int ReferenceFieldNumber = 3;
    private string reference_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Reference {
      get { return reference_; }
      set {
        reference_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "amount" field.</summary>
    public const int AmountFieldNumber = 4;
    private long amount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Amount {
      get { return amount_; }
      set {
        amount_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 100;
    private global::Google.Protobuf.WellKnownTypes.Any data_;
    /// <summary>
    /// Payment method specific information
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RefundRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RefundRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PaymentId != other.PaymentId) return false;
      if (RequestId != other.RequestId) return false;
      if (Reference != other.Reference) return false;
      if (Amount != other.Amount) return false;
      if (!object.Equals(Data, other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PaymentId.Length != 0) hash ^= PaymentId.GetHashCode();
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (Reference.Length != 0) hash ^= Reference.GetHashCode();
      if (Amount != 0L) hash ^= Amount.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PaymentId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PaymentId);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestId);
      }
      if (Reference.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Reference);
      }
      if (Amount != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Amount);
      }
      if (data_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PaymentId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PaymentId);
      }
      if (RequestId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(RequestId);
      }
      if (Reference.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Reference);
      }
      if (Amount != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Amount);
      }
      if (data_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PaymentId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PaymentId);
      }
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (Reference.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Reference);
      }
      if (Amount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Amount);
      }
      if (data_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RefundRequest other) {
      if (other == null) {
        return;
      }
      if (other.PaymentId.Length != 0) {
        PaymentId = other.PaymentId;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.Reference.Length != 0) {
        Reference = other.Reference;
      }
      if (other.Amount != 0L) {
        Amount = other.Amount;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Data.MergeFrom(other.Data);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PaymentId = input.ReadString();
            break;
          }
          case 18: {
            RequestId = input.ReadString();
            break;
          }
          case 26: {
            Reference = input.ReadString();
            break;
          }
          case 32: {
            Amount = input.ReadInt64();
            break;
          }
          case 802: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PaymentId = input.ReadString();
            break;
          }
          case 18: {
            RequestId = input.ReadString();
            break;
          }
          case 26: {
            Reference = input.ReadString();
            break;
          }
          case 32: {
            Amount = input.ReadInt64();
            break;
          }
          case 802: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Data);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class RefundResponse : pb::IMessage<RefundResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RefundResponse> _parser = new pb::MessageParser<RefundResponse>(() => new RefundResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RefundResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentProcessingServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefundResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefundResponse(RefundResponse other) : this() {
      refundId_ = other.refundId_;
      data_ = other.data_ != null ? other.data_.Clone() : null;
      status_ = other.status_ != null ? other.status_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefundResponse Clone() {
      return new RefundResponse(this);
    }

    /// <summary>Field number for the "refund_id" field.</summary>
    public const int RefundIdFieldNumber = 1;
    private string refundId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RefundId {
      get { return refundId_; }
      set {
        refundId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 100;
    private global::Google.Protobuf.WellKnownTypes.Any data_;
    /// <summary>
    /// Payment method specific information
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 101;
    private global::Relay.Status status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Relay.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RefundResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RefundResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RefundId != other.RefundId) return false;
      if (!object.Equals(Data, other.Data)) return false;
      if (!object.Equals(Status, other.Status)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RefundId.Length != 0) hash ^= RefundId.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      if (status_ != null) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RefundId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RefundId);
      }
      if (data_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(Data);
      }
      if (status_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RefundId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RefundId);
      }
      if (data_ != null) {
        output.WriteRawTag(162, 6);
        output.WriteMessage(Data);
      }
      if (status_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RefundId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RefundId);
      }
      if (data_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (status_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RefundResponse other) {
      if (other == null) {
        return;
      }
      if (other.RefundId.Length != 0) {
        RefundId = other.RefundId;
      }
      if (other.data_ != null) {
        if (data_ == null) {
          Data = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        Data.MergeFrom(other.Data);
      }
      if (other.status_ != null) {
        if (status_ == null) {
          Status = new global::Relay.Status();
        }
        Status.MergeFrom(other.Status);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RefundId = input.ReadString();
            break;
          }
          case 802: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Data);
            break;
          }
          case 810: {
            if (status_ == null) {
              Status = new global::Relay.Status();
            }
            input.ReadMessage(Status);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RefundId = input.ReadString();
            break;
          }
          case 802: {
            if (data_ == null) {
              Data = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(Data);
            break;
          }
          case 810: {
            if (status_ == null) {
              Status = new global::Relay.Status();
            }
            input.ReadMessage(Status);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetSummaryRequest : pb::IMessage<GetSummaryRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetSummaryRequest> _parser = new pb::MessageParser<GetSummaryRequest>(() => new GetSummaryRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetSummaryRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentProcessingServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetSummaryRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetSummaryRequest(GetSummaryRequest other) : this() {
      paymentId_ = other.paymentId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetSummaryRequest Clone() {
      return new GetSummaryRequest(this);
    }

    /// <summary>Field number for the "payment_id" field.</summary>
    public const int PaymentIdFieldNumber = 1;
    private string paymentId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PaymentId {
      get { return paymentId_; }
      set {
        paymentId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetSummaryRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetSummaryRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PaymentId != other.PaymentId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PaymentId.Length != 0) hash ^= PaymentId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PaymentId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PaymentId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PaymentId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PaymentId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PaymentId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PaymentId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetSummaryRequest other) {
      if (other == null) {
        return;
      }
      if (other.PaymentId.Length != 0) {
        PaymentId = other.PaymentId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PaymentId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PaymentId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetSummaryResponse : pb::IMessage<GetSummaryResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetSummaryResponse> _parser = new pb::MessageParser<GetSummaryResponse>(() => new GetSummaryResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetSummaryResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentProcessingServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetSummaryResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetSummaryResponse(GetSummaryResponse other) : this() {
      authorizedAmount_ = other.authorizedAmount_;
      chargedAmount_ = other.chargedAmount_;
      canceledAmount_ = other.canceledAmount_;
      refundedAmount_ = other.refundedAmount_;
      currency_ = other.currency_;
      status_ = other.status_ != null ? other.status_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetSummaryResponse Clone() {
      return new GetSummaryResponse(this);
    }

    /// <summary>Field number for the "authorized_amount" field.</summary>
    public const int AuthorizedAmountFieldNumber = 1;
    private long authorizedAmount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AuthorizedAmount {
      get { return authorizedAmount_; }
      set {
        authorizedAmount_ = value;
      }
    }

    /// <summary>Field number for the "charged_amount" field.</summary>
    public const int ChargedAmountFieldNumber = 2;
    private long chargedAmount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ChargedAmount {
      get { return chargedAmount_; }
      set {
        chargedAmount_ = value;
      }
    }

    /// <summary>Field number for the "canceled_amount" field.</summary>
    public const int CanceledAmountFieldNumber = 3;
    private long canceledAmount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CanceledAmount {
      get { return canceledAmount_; }
      set {
        canceledAmount_ = value;
      }
    }

    /// <summary>Field number for the "refunded_amount" field.</summary>
    public const int RefundedAmountFieldNumber = 4;
    private long refundedAmount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RefundedAmount {
      get { return refundedAmount_; }
      set {
        refundedAmount_ = value;
      }
    }

    /// <summary>Field number for the "currency" field.</summary>
    public const int CurrencyFieldNumber = 5;
    private string currency_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Currency {
      get { return currency_; }
      set {
        currency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 101;
    private global::Relay.Status status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Relay.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetSummaryResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetSummaryResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AuthorizedAmount != other.AuthorizedAmount) return false;
      if (ChargedAmount != other.ChargedAmount) return false;
      if (CanceledAmount != other.CanceledAmount) return false;
      if (RefundedAmount != other.RefundedAmount) return false;
      if (Currency != other.Currency) return false;
      if (!object.Equals(Status, other.Status)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AuthorizedAmount != 0L) hash ^= AuthorizedAmount.GetHashCode();
      if (ChargedAmount != 0L) hash ^= ChargedAmount.GetHashCode();
      if (CanceledAmount != 0L) hash ^= CanceledAmount.GetHashCode();
      if (RefundedAmount != 0L) hash ^= RefundedAmount.GetHashCode();
      if (Currency.Length != 0) hash ^= Currency.GetHashCode();
      if (status_ != null) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AuthorizedAmount != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(AuthorizedAmount);
      }
      if (ChargedAmount != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ChargedAmount);
      }
      if (CanceledAmount != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CanceledAmount);
      }
      if (RefundedAmount != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(RefundedAmount);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Currency);
      }
      if (status_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AuthorizedAmount != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(AuthorizedAmount);
      }
      if (ChargedAmount != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(ChargedAmount);
      }
      if (CanceledAmount != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(CanceledAmount);
      }
      if (RefundedAmount != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(RefundedAmount);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Currency);
      }
      if (status_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AuthorizedAmount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AuthorizedAmount);
      }
      if (ChargedAmount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ChargedAmount);
      }
      if (CanceledAmount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CanceledAmount);
      }
      if (RefundedAmount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RefundedAmount);
      }
      if (Currency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Currency);
      }
      if (status_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetSummaryResponse other) {
      if (other == null) {
        return;
      }
      if (other.AuthorizedAmount != 0L) {
        AuthorizedAmount = other.AuthorizedAmount;
      }
      if (other.ChargedAmount != 0L) {
        ChargedAmount = other.ChargedAmount;
      }
      if (other.CanceledAmount != 0L) {
        CanceledAmount = other.CanceledAmount;
      }
      if (other.RefundedAmount != 0L) {
        RefundedAmount = other.RefundedAmount;
      }
      if (other.Currency.Length != 0) {
        Currency = other.Currency;
      }
      if (other.status_ != null) {
        if (status_ == null) {
          Status = new global::Relay.Status();
        }
        Status.MergeFrom(other.Status);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AuthorizedAmount = input.ReadInt64();
            break;
          }
          case 16: {
            ChargedAmount = input.ReadInt64();
            break;
          }
          case 24: {
            CanceledAmount = input.ReadInt64();
            break;
          }
          case 32: {
            RefundedAmount = input.ReadInt64();
            break;
          }
          case 42: {
            Currency = input.ReadString();
            break;
          }
          case 810: {
            if (status_ == null) {
              Status = new global::Relay.Status();
            }
            input.ReadMessage(Status);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AuthorizedAmount = input.ReadInt64();
            break;
          }
          case 16: {
            ChargedAmount = input.ReadInt64();
            break;
          }
          case 24: {
            CanceledAmount = input.ReadInt64();
            break;
          }
          case 32: {
            RefundedAmount = input.ReadInt64();
            break;
          }
          case 42: {
            Currency = input.ReadString();
            break;
          }
          case 810: {
            if (status_ == null) {
              Status = new global::Relay.Status();
            }
            input.ReadMessage(Status);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetOperationsSummaryRequest : pb::IMessage<GetOperationsSummaryRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetOperationsSummaryRequest> _parser = new pb::MessageParser<GetOperationsSummaryRequest>(() => new GetOperationsSummaryRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetOperationsSummaryRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentProcessingServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetOperationsSummaryRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetOperationsSummaryRequest(GetOperationsSummaryRequest other) : this() {
      paymentId_ = other.paymentId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetOperationsSummaryRequest Clone() {
      return new GetOperationsSummaryRequest(this);
    }

    /// <summary>Field number for the "payment_id" field.</summary>
    public const int PaymentIdFieldNumber = 1;
    private string paymentId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PaymentId {
      get { return paymentId_; }
      set {
        paymentId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetOperationsSummaryRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetOperationsSummaryRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PaymentId != other.PaymentId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PaymentId.Length != 0) hash ^= PaymentId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PaymentId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PaymentId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PaymentId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PaymentId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PaymentId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PaymentId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetOperationsSummaryRequest other) {
      if (other == null) {
        return;
      }
      if (other.PaymentId.Length != 0) {
        PaymentId = other.PaymentId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PaymentId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PaymentId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetOperationsSummaryResponse : pb::IMessage<GetOperationsSummaryResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetOperationsSummaryResponse> _parser = new pb::MessageParser<GetOperationsSummaryResponse>(() => new GetOperationsSummaryResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetOperationsSummaryResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Relay.Processing.V1.PaymentProcessingServiceReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetOperationsSummaryResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetOperationsSummaryResponse(GetOperationsSummaryResponse other) : this() {
      operations_ = other.operations_.Clone();
      status_ = other.status_ != null ? other.status_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetOperationsSummaryResponse Clone() {
      return new GetOperationsSummaryResponse(this);
    }

    /// <summary>Field number for the "operations" field.</summary>
    public const int OperationsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Relay.Processing.V1.OperationSummary> _repeated_operations_codec
        = pb::FieldCodec.ForMessage(10, global::Relay.Processing.V1.OperationSummary.Parser);
    private readonly pbc::RepeatedField<global::Relay.Processing.V1.OperationSummary> operations_ = new pbc::RepeatedField<global::Relay.Processing.V1.OperationSummary>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Relay.Processing.V1.OperationSummary> Operations {
      get { return operations_; }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 101;
    private global::Relay.Status status_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Relay.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetOperationsSummaryResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetOperationsSummaryResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!operations_.Equals(other.operations_)) return false;
      if (!object.Equals(Status, other.Status)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= operations_.GetHashCode();
      if (status_ != null) hash ^= Status.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      operations_.WriteTo(output, _repeated_operations_codec);
      if (status_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      operations_.WriteTo(ref output, _repeated_operations_codec);
      if (status_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(Status);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += operations_.CalculateSize(_repeated_operations_codec);
      if (status_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Status);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetOperationsSummaryResponse other) {
      if (other == null) {
        return;
      }
      operations_.Add(other.operations_);
      if (other.status_ != null) {
        if (status_ == null) {
          Status = new global::Relay.Status();
        }
        Status.MergeFrom(other.Status);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            operations_.AddEntriesFrom(input, _repeated_operations_codec);
            break;
          }
          case 810: {
            if (status_ == null) {
              Status = new global::Relay.Status();
            }
            input.ReadMessage(Status);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            operations_.AddEntriesFrom(ref input, _repeated_operations_codec);
            break;
          }
          case 810: {
            if (status_ == null) {
              Status = new global::Relay.Status();
            }
            input.ReadMessage(Status);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
