// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: relay/onboarding/v1/payment_method_onboarding_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Relay.Onboarding.V1 {
  public static partial class PaymentMethodOnboarding
  {
    static readonly string __ServiceName = "relay.onboarding.v1.PaymentMethodOnboarding";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Onboarding.V1.InitializeRequest> __Marshaller_relay_onboarding_v1_InitializeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Onboarding.V1.InitializeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Onboarding.V1.InitializeResponse> __Marshaller_relay_onboarding_v1_InitializeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Onboarding.V1.InitializeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Onboarding.V1.UpdateRequest> __Marshaller_relay_onboarding_v1_UpdateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Onboarding.V1.UpdateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Onboarding.V1.UpdateResponse> __Marshaller_relay_onboarding_v1_UpdateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Onboarding.V1.UpdateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Onboarding.V1.GetRequest> __Marshaller_relay_onboarding_v1_GetRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Onboarding.V1.GetRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Onboarding.V1.GetResponse> __Marshaller_relay_onboarding_v1_GetResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Onboarding.V1.GetResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Onboarding.V1.CompletelyNew> __Marshaller_relay_onboarding_v1_CompletelyNew = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Onboarding.V1.CompletelyNew.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Onboarding.V1.NewIndeed> __Marshaller_relay_onboarding_v1_NewIndeed = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Onboarding.V1.NewIndeed.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Onboarding.V1.TryNested> __Marshaller_relay_onboarding_v1_TryNested = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Onboarding.V1.TryNested.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Relay.Onboarding.V1.ResNested> __Marshaller_relay_onboarding_v1_ResNested = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Relay.Onboarding.V1.ResNested.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Relay.Onboarding.V1.InitializeRequest, global::Relay.Onboarding.V1.InitializeResponse> __Method_Initialize = new grpc::Method<global::Relay.Onboarding.V1.InitializeRequest, global::Relay.Onboarding.V1.InitializeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Initialize",
        __Marshaller_relay_onboarding_v1_InitializeRequest,
        __Marshaller_relay_onboarding_v1_InitializeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Relay.Onboarding.V1.UpdateRequest, global::Relay.Onboarding.V1.UpdateResponse> __Method_Update = new grpc::Method<global::Relay.Onboarding.V1.UpdateRequest, global::Relay.Onboarding.V1.UpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Update",
        __Marshaller_relay_onboarding_v1_UpdateRequest,
        __Marshaller_relay_onboarding_v1_UpdateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Relay.Onboarding.V1.GetRequest, global::Relay.Onboarding.V1.GetResponse> __Method_Get = new grpc::Method<global::Relay.Onboarding.V1.GetRequest, global::Relay.Onboarding.V1.GetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_relay_onboarding_v1_GetRequest,
        __Marshaller_relay_onboarding_v1_GetResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Relay.Onboarding.V1.CompletelyNew, global::Relay.Onboarding.V1.NewIndeed> __Method_New = new grpc::Method<global::Relay.Onboarding.V1.CompletelyNew, global::Relay.Onboarding.V1.NewIndeed>(
        grpc::MethodType.Unary,
        __ServiceName,
        "New",
        __Marshaller_relay_onboarding_v1_CompletelyNew,
        __Marshaller_relay_onboarding_v1_NewIndeed);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Relay.Onboarding.V1.TryNested, global::Relay.Onboarding.V1.ResNested> __Method_Nested = new grpc::Method<global::Relay.Onboarding.V1.TryNested, global::Relay.Onboarding.V1.ResNested>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Nested",
        __Marshaller_relay_onboarding_v1_TryNested,
        __Marshaller_relay_onboarding_v1_ResNested);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Relay.Onboarding.V1.PaymentMethodOnboardingServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PaymentMethodOnboarding</summary>
    [grpc::BindServiceMethod(typeof(PaymentMethodOnboarding), "BindService")]
    public abstract partial class PaymentMethodOnboardingBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Relay.Onboarding.V1.InitializeResponse> Initialize(global::Relay.Onboarding.V1.InitializeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Relay.Onboarding.V1.UpdateResponse> Update(global::Relay.Onboarding.V1.UpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Relay.Onboarding.V1.GetResponse> Get(global::Relay.Onboarding.V1.GetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Relay.Onboarding.V1.NewIndeed> New(global::Relay.Onboarding.V1.CompletelyNew request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Relay.Onboarding.V1.ResNested> Nested(global::Relay.Onboarding.V1.TryNested request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PaymentMethodOnboarding</summary>
    public partial class PaymentMethodOnboardingClient : grpc::ClientBase<PaymentMethodOnboardingClient>
    {
      /// <summary>Creates a new client for PaymentMethodOnboarding</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public PaymentMethodOnboardingClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PaymentMethodOnboarding that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public PaymentMethodOnboardingClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected PaymentMethodOnboardingClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected PaymentMethodOnboardingClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Onboarding.V1.InitializeResponse Initialize(global::Relay.Onboarding.V1.InitializeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Initialize(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Onboarding.V1.InitializeResponse Initialize(global::Relay.Onboarding.V1.InitializeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Initialize, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Onboarding.V1.InitializeResponse> InitializeAsync(global::Relay.Onboarding.V1.InitializeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return InitializeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Onboarding.V1.InitializeResponse> InitializeAsync(global::Relay.Onboarding.V1.InitializeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Initialize, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Onboarding.V1.UpdateResponse Update(global::Relay.Onboarding.V1.UpdateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Update(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Onboarding.V1.UpdateResponse Update(global::Relay.Onboarding.V1.UpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Update, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Onboarding.V1.UpdateResponse> UpdateAsync(global::Relay.Onboarding.V1.UpdateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Onboarding.V1.UpdateResponse> UpdateAsync(global::Relay.Onboarding.V1.UpdateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Update, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Onboarding.V1.GetResponse Get(global::Relay.Onboarding.V1.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Get(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Onboarding.V1.GetResponse Get(global::Relay.Onboarding.V1.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Get, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Onboarding.V1.GetResponse> GetAsync(global::Relay.Onboarding.V1.GetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Onboarding.V1.GetResponse> GetAsync(global::Relay.Onboarding.V1.GetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Get, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Onboarding.V1.NewIndeed New(global::Relay.Onboarding.V1.CompletelyNew request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return New(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Onboarding.V1.NewIndeed New(global::Relay.Onboarding.V1.CompletelyNew request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_New, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Onboarding.V1.NewIndeed> NewAsync(global::Relay.Onboarding.V1.CompletelyNew request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return NewAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Onboarding.V1.NewIndeed> NewAsync(global::Relay.Onboarding.V1.CompletelyNew request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_New, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Onboarding.V1.ResNested Nested(global::Relay.Onboarding.V1.TryNested request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Nested(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Relay.Onboarding.V1.ResNested Nested(global::Relay.Onboarding.V1.TryNested request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Nested, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Onboarding.V1.ResNested> NestedAsync(global::Relay.Onboarding.V1.TryNested request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return NestedAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Relay.Onboarding.V1.ResNested> NestedAsync(global::Relay.Onboarding.V1.TryNested request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Nested, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override PaymentMethodOnboardingClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PaymentMethodOnboardingClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(PaymentMethodOnboardingBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Initialize, serviceImpl.Initialize)
          .AddMethod(__Method_Update, serviceImpl.Update)
          .AddMethod(__Method_Get, serviceImpl.Get)
          .AddMethod(__Method_New, serviceImpl.New)
          .AddMethod(__Method_Nested, serviceImpl.Nested).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PaymentMethodOnboardingBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Initialize, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Relay.Onboarding.V1.InitializeRequest, global::Relay.Onboarding.V1.InitializeResponse>(serviceImpl.Initialize));
      serviceBinder.AddMethod(__Method_Update, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Relay.Onboarding.V1.UpdateRequest, global::Relay.Onboarding.V1.UpdateResponse>(serviceImpl.Update));
      serviceBinder.AddMethod(__Method_Get, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Relay.Onboarding.V1.GetRequest, global::Relay.Onboarding.V1.GetResponse>(serviceImpl.Get));
      serviceBinder.AddMethod(__Method_New, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Relay.Onboarding.V1.CompletelyNew, global::Relay.Onboarding.V1.NewIndeed>(serviceImpl.New));
      serviceBinder.AddMethod(__Method_Nested, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Relay.Onboarding.V1.TryNested, global::Relay.Onboarding.V1.ResNested>(serviceImpl.Nested));
    }

  }
}
#endregion
